#env = AQ_DRM_DEVICES,/dev/dri/card0
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia


$mod = SUPER
$terminal = kitty

bind = $mod, Return, exec, $terminal
bind = $mod, c, killactive

# Move focus
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, down, movefocus, d
bind = $mod, up, movefocus, u


# Switch workspaces with mainMod + [0-9]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10
# move/resize using mouse

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

#TODO shouldnt be hardcoded
#monitor = eDP-1, 1920x1080@60, 1920x0, 1
#monitor = HDMI-A-1, 1920x1080@60, 0x0, 1 


input {
	kb_layout = de
}

opengl {
	nvidia_anti_flicker = false
}
